/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package senior.citizen.record.system.barangay_classify;

/**
 *
 * @author Administrator
 */
public class Barangay extends javax.swing.JFrame {

    private static final String[] brgyList = {
        "Antipolo", "Ariendo", "Bantog", "Calaanan", "Commercial", "Cruz", "Curva",
        "Digmala", "Caingin", "Labi", "Larcon", "Lusok", "Macabaklay", "Matanggol",
        "Mantile", "Olibete", "Palomaria", "Pesa", "Rizal", "Sampalukan", "San Roque",
        "Santor", "Sinipit", "Sisilang", "Social", "Togatog", "Tulay na bato", "Vega"
    };

    /**
     * Creates new form Barangay
     */
    public Barangay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAntipolo = new javax.swing.JButton();
        btnAriendo = new javax.swing.JButton();
        btnBantog = new javax.swing.JButton();
        btnCalaanan = new javax.swing.JButton();
        btnCommercial = new javax.swing.JButton();
        btnCruz = new javax.swing.JButton();
        btnCurva = new javax.swing.JButton();
        btnDigmala = new javax.swing.JButton();
        btnCaingin = new javax.swing.JButton();
        btnLabi = new javax.swing.JButton();
        btnLarcon = new javax.swing.JButton();
        btnLusok = new javax.swing.JButton();
        btnMacabaklay = new javax.swing.JButton();
        btnMatanggol = new javax.swing.JButton();
        btnMantile = new javax.swing.JButton();
        btnOlibete = new javax.swing.JButton();
        btnPalomaria = new javax.swing.JButton();
        btnPesa = new javax.swing.JButton();
        btnRizal = new javax.swing.JButton();
        btnSampalukan = new javax.swing.JButton();
        btnSanRoque = new javax.swing.JButton();
        btnSantor = new javax.swing.JButton();
        btnSinipit = new javax.swing.JButton();
        btnSisilang = new javax.swing.JButton();
        btnSocial = new javax.swing.JButton();
        btnTogatog = new javax.swing.JButton();
        btnTulaynaBato = new javax.swing.JButton();
        btnVega = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAntipolo.setText("Antipolo");
        btnAntipolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntipoloActionPerformed(evt);
            }
        });

        btnAriendo.setText("Ariendo");
        btnAriendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAriendoActionPerformed(evt);
            }
        });

        btnBantog.setText("Bantog");
        btnBantog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBantogActionPerformed(evt);
            }
        });

        btnCalaanan.setText("Calaanan");
        btnCalaanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalaananActionPerformed(evt);
            }
        });

        btnCommercial.setText("Commercial");
        btnCommercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommercialActionPerformed(evt);
            }
        });

        btnCruz.setText("Cruz");
        btnCruz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCruzActionPerformed(evt);
            }
        });

        btnCurva.setText("Curva");
        btnCurva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurvaActionPerformed(evt);
            }
        });

        btnDigmala.setText("Digmala");
        btnDigmala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigmalaActionPerformed(evt);
            }
        });

        btnCaingin.setText("Caingin");
        btnCaingin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCainginActionPerformed(evt);
            }
        });

        btnLabi.setText("Labi");
        btnLabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabiActionPerformed(evt);
            }
        });

        btnLarcon.setText("Larcon");
        btnLarcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLarconActionPerformed(evt);
            }
        });

        btnLusok.setText("Lusok");
        btnLusok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLusokActionPerformed(evt);
            }
        });

        btnMacabaklay.setText("Macabaklay");
        btnMacabaklay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMacabaklayActionPerformed(evt);
            }
        });

        btnMatanggol.setText("Matanggol");
        btnMatanggol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatanggolActionPerformed(evt);
            }
        });

        btnMantile.setText("Mantile");
        btnMantile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantileActionPerformed(evt);
            }
        });

        btnOlibete.setText("Olibete");
        btnOlibete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOlibeteActionPerformed(evt);
            }
        });

        btnPalomaria.setText("Palomaria");
        btnPalomaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalomariaActionPerformed(evt);
            }
        });

        btnPesa.setText("Pesa");
        btnPesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesaActionPerformed(evt);
            }
        });

        btnRizal.setText("Rizal");
        btnRizal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRizalActionPerformed(evt);
            }
        });

        btnSampalukan.setText("Sampalukan");
        btnSampalukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSampalukanActionPerformed(evt);
            }
        });

        btnSanRoque.setText("San Roque");
        btnSanRoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanRoqueActionPerformed(evt);
            }
        });

        btnSantor.setText("Santor");
        btnSantor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSantorActionPerformed(evt);
            }
        });

        btnSinipit.setText("Sinipit");
        btnSinipit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinipitActionPerformed(evt);
            }
        });

        btnSisilang.setText("Sisilang");
        btnSisilang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSisilangActionPerformed(evt);
            }
        });

        btnSocial.setText("Social");
        btnSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSocialActionPerformed(evt);
            }
        });

        btnTogatog.setText("Togatog");
        btnTogatog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTogatogActionPerformed(evt);
            }
        });

        btnTulaynaBato.setText("Tulay na bato");
        btnTulaynaBato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTulaynaBatoActionPerformed(evt);
            }
        });

        btnVega.setText("Vega");
        btnVega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVegaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCommercial, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnCaingin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCruz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLabi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMacabaklay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMatanggol, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAntipolo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAriendo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSanRoque, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSantor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTogatog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPalomaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCurva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBantog, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(btnLarcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMantile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRizal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSinipit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTulaynaBato, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalaanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDigmala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLusok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOlibete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSampalukan, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnSisilang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAntipolo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAriendo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBantog, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalaanan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCommercial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCruz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCurva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigmala, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaingin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLabi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLarcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLusok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMacabaklay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMatanggol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMantile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOlibete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPalomaria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRizal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSampalukan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSanRoque, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSantor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSinipit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSisilang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnTogatog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTulaynaBato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAntipoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntipoloActionPerformed
        openSeniorRecords(brgyList[0]);
    }//GEN-LAST:event_btnAntipoloActionPerformed

    private void btnAriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAriendoActionPerformed
        openSeniorRecords(brgyList[1]);
    }//GEN-LAST:event_btnAriendoActionPerformed

    private void btnBantogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBantogActionPerformed
        openSeniorRecords(brgyList[2]);
    }//GEN-LAST:event_btnBantogActionPerformed

    private void btnCalaananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalaananActionPerformed
        openSeniorRecords(brgyList[3]);
    }//GEN-LAST:event_btnCalaananActionPerformed

    private void btnCommercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommercialActionPerformed
        openSeniorRecords(brgyList[4]);
    }//GEN-LAST:event_btnCommercialActionPerformed

    private void btnCruzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCruzActionPerformed
        openSeniorRecords(brgyList[5]);
    }//GEN-LAST:event_btnCruzActionPerformed

    private void btnCurvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurvaActionPerformed
        openSeniorRecords(brgyList[6]);
    }//GEN-LAST:event_btnCurvaActionPerformed

    private void btnDigmalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigmalaActionPerformed
        openSeniorRecords(brgyList[7]);
    }//GEN-LAST:event_btnDigmalaActionPerformed

    private void btnCainginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCainginActionPerformed
        openSeniorRecords(brgyList[8]);
    }//GEN-LAST:event_btnCainginActionPerformed

    private void btnLabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabiActionPerformed
        openSeniorRecords(brgyList[9]);
    }//GEN-LAST:event_btnLabiActionPerformed

    private void btnLarconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLarconActionPerformed
        openSeniorRecords(brgyList[10]);
    }//GEN-LAST:event_btnLarconActionPerformed

    private void btnLusokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLusokActionPerformed
        openSeniorRecords(brgyList[11]);
    }//GEN-LAST:event_btnLusokActionPerformed

    private void btnMacabaklayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMacabaklayActionPerformed
        openSeniorRecords(brgyList[12]);

    }//GEN-LAST:event_btnMacabaklayActionPerformed

    private void btnMatanggolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatanggolActionPerformed
        openSeniorRecords(brgyList[13]);

    }//GEN-LAST:event_btnMatanggolActionPerformed

    private void btnMantileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantileActionPerformed
        openSeniorRecords(brgyList[14]);
    }//GEN-LAST:event_btnMantileActionPerformed

    private void btnOlibeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlibeteActionPerformed
        openSeniorRecords(brgyList[15]);
    }//GEN-LAST:event_btnOlibeteActionPerformed

    private void btnPalomariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalomariaActionPerformed
        openSeniorRecords(brgyList[16]);
    }//GEN-LAST:event_btnPalomariaActionPerformed

    private void btnPesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesaActionPerformed
        openSeniorRecords(brgyList[17]);
    }//GEN-LAST:event_btnPesaActionPerformed

    private void btnRizalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRizalActionPerformed
        openSeniorRecords(brgyList[18]);
    }//GEN-LAST:event_btnRizalActionPerformed

    private void btnSampalukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSampalukanActionPerformed
        openSeniorRecords(brgyList[19]);
    }//GEN-LAST:event_btnSampalukanActionPerformed

    private void btnSanRoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanRoqueActionPerformed
        openSeniorRecords(brgyList[20]);
    }//GEN-LAST:event_btnSanRoqueActionPerformed

    private void btnSantorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSantorActionPerformed
        openSeniorRecords(brgyList[21]);
    }//GEN-LAST:event_btnSantorActionPerformed

    private void btnSinipitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinipitActionPerformed
        openSeniorRecords(brgyList[22]);
    }//GEN-LAST:event_btnSinipitActionPerformed

    private void btnSisilangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSisilangActionPerformed
        openSeniorRecords(brgyList[23]);
    }//GEN-LAST:event_btnSisilangActionPerformed

    private void btnSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSocialActionPerformed
        openSeniorRecords(brgyList[24]);
    }//GEN-LAST:event_btnSocialActionPerformed

    private void btnTogatogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTogatogActionPerformed
        openSeniorRecords(brgyList[25]);
    }//GEN-LAST:event_btnTogatogActionPerformed

    private void btnTulaynaBatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTulaynaBatoActionPerformed
        openSeniorRecords(brgyList[26]);
    }//GEN-LAST:event_btnTulaynaBatoActionPerformed

    private void btnVegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVegaActionPerformed
        openSeniorRecords(brgyList[27]);
    }//GEN-LAST:event_btnVegaActionPerformed

    private void openSeniorRecords(String brgy) {
        SeniorRecords seniorRecords = new SeniorRecords(brgy);
        seniorRecords.setVisible(true);
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barangay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barangay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barangay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barangay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barangay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAntipolo;
    private javax.swing.JButton btnAriendo;
    private javax.swing.JButton btnBantog;
    private javax.swing.JButton btnCaingin;
    private javax.swing.JButton btnCalaanan;
    private javax.swing.JButton btnCommercial;
    private javax.swing.JButton btnCruz;
    private javax.swing.JButton btnCurva;
    private javax.swing.JButton btnDigmala;
    private javax.swing.JButton btnLabi;
    private javax.swing.JButton btnLarcon;
    private javax.swing.JButton btnLusok;
    private javax.swing.JButton btnMacabaklay;
    private javax.swing.JButton btnMantile;
    private javax.swing.JButton btnMatanggol;
    private javax.swing.JButton btnOlibete;
    private javax.swing.JButton btnPalomaria;
    private javax.swing.JButton btnPesa;
    private javax.swing.JButton btnRizal;
    private javax.swing.JButton btnSampalukan;
    private javax.swing.JButton btnSanRoque;
    private javax.swing.JButton btnSantor;
    private javax.swing.JButton btnSinipit;
    private javax.swing.JButton btnSisilang;
    private javax.swing.JButton btnSocial;
    private javax.swing.JButton btnTogatog;
    private javax.swing.JButton btnTulaynaBato;
    private javax.swing.JButton btnVega;
    // End of variables declaration//GEN-END:variables
}
